const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
const GET_ADD_DATA_REQUESTED = 'GET_ADD_DATA_REQUESTED';
const GET_DATA_SUCCEEDED = 'GET_DATA_SUCCEEDED';
const GET_ADD_DATA_SUCCEEDED = 'GET_ADD_DATA_SUCCEEDED';
const GET_DATA_FAILED = 'GET_DATA_FAILED';
const CLEAR_ADD_DATA = 'CLEAR_ADD_DATA';

export { 
    GET_DATA_REQUESTED,
    GET_ADD_DATA_REQUESTED,
    GET_DATA_SUCCEEDED,
    GET_ADD_DATA_SUCCEEDED,
    GET_DATA_FAILED,
    CLEAR_ADD_DATA
};
