export { default as Home } from './Home'
export { default as Hotel } from './Hotel'
export { default as NotFound } from './NotFound'
export { default as LogIn } from './LogIn'
export { default as SignUp } from './SignUp'
