export const CAR_PLACEHOLDER = 'Марка'
export const MODEL_PLACEHOLDER = 'Модель'
export const YEAR_OF_ISSUE_PLACEHOLDER = 'Год выпуска'
export const COST_PLACEHOLDER = 'Стоимость'
export const ADD_BUTTON = 'Добавить'
