export const parsingData = data => ({
    id: data.id,
    name: data.name,
    edatapansion: data.edatapansion,
    army_type: data.army_type,
    team_bonus: data.team_bonus,
    created_in: data.created_in,
    civilization_bonus: data.civilization_bonus,
    unique_unit: data.unique_unit,
    unique_tech: data.unique_tech,
    description: data.description,
    age: data.age,
    cost: data.cost,
    build_time: data.build_time,
    reload_time: data.reload_time,
    attack_delay: data.attack_delay,
    movement_rate: data.movement_rate,
    line_of_sight: data.line_of_sight,
    hit_points: data.hit_points,
    range: data.range,
    attack: data.attack,
    attack_bonus: data.attack_bonus,
    armor: data.armor,
    accuracy: data.accuracy,
    special: data.special,
    applies_to: data.applies_to
})