export const GET_DATA_REQUESTED = "GET_DATA_REQUESTED";
export const GET_DATA_SUCCEED = "GET_DATA_SUCCEED";
export const GET_DATA_FAILED = "GET_DATA_FAILED";

export const GET_DETAILS_REQUESTED = "GET_DETAILS_REQUESTED";
export const GET_DETAILS_SUCCEED = "GET_DETAILS_SUCCEED";
export const GET_DETAILS_FAILED = "GET_DETAILS_FAILED";
