export const GET_POSTS_REQUESTED = "GET_POSTS_REQUESTED";
export const GET_POSTS_SUCCEED = "GET_POSTS_SUCCEED";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const GET_TODOS_REQUESTED = "GET_TODOS_REQUESTED";
export const GET_TODOS_SUCCEED = "GET_TODOS_SUCCEED";
export const GET_TODOS_FAILED = "GET_TODOS_FAILED";

export const GET_POST_DETAILS_REQUESTED = "GET_POST_DETAILS_REQUESTED";
export const GET_POST_DETAILS_SUCCEED = "GET_POST_DETAILS_SUCCEED";
export const GET_POST_DETAILS_FAILED = "GET_POST_DETAILS_FAILED ";

export const GET_TODO_DETAILS_REQUESTED = "GET_TODO_DETAILS_REQUESTED";
export const GET_TODO_DETAILS_SUCCEED = "GET_TODO_DETAILS_SUCCEED";
export const GET_TODO_DETAILS_FAILED = "GET_TODO_DETAILS_FAILED";
